esphome:
  name: bedside-david
  platform: ESP8266
  board: d1_mini


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "vGXs6QggfM1tTNEXF+vnW/+BYCYIQmI4MVfqqvX/Q90="

ota:
  password: "8091b1e34a6f15c0bf80867c0bb576a9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dfg Fallback Hotspot"
    password: "CdkFB2alJAEF"

captive_portal:
substitutions:
  $light_1: "11%"
  $light_2: "50%"  
  $rot_Service_1: "switch.toggle"   
  $rot_cockwise: "switch.bedroom_sound_volume" 
  $rot_countercockwise: "switch.bedroom_sound_volume_2"      

  $push_button_service: "switch.toggle"   
  $push_button: "switch.bedroom_tv "

  $button_Service_1_click: "light.turn_off"   
  $button_1_click: "light.bedroom_lights"   
  $button_Service_1_hold: "light.turn_on"   
  $button_1_hold: "light.bedroom_lights"   

  $button_Service_2_click: "switch.toggle"   
  $button_2_click: "switch.little_tv_relay"   
  $button_Service_2_hold: "input_boolean.turn_on"   
  $button_2_hold: "input_boolean.morning_holdd "   

  $button_Service_3_click: "switch.toggle"   
  $button_3_click: "switch.bedroom_fan_speed"   
  $button_Service_3_hold: "switch.toggle"   
  $button_3_hold: "switch.bedroom_fan" 

  $button_Service_4_click: "cover.toggle"   
  $button_4_click: "cover.bedroom_blinds"   
  $button_Service_4_hold: "cover.bedroom_blinds"   
  $button_4_hold: "cover.toggle"  

  $pixel_1: "binary_sensor.doors"  
  $pixel_2: "switch.heater"    



sensor:
  - platform: rotary_encoder
    id: d5525
    min_value: 0
    max_value: 100
    resolution: 1
    pin_a: D3
    pin_b: D4
    on_value:    
    - delay: 1s
    - sensor.rotary_encoder.set_value:
       id: d5525
       value: 50
    on_clockwise:
        if:
          condition:
            sensor.in_range:
              id: d5525
              above: 51.0
          then:
            - homeassistant.service:
                service: $rot_Service_1
                data:
                  entity_id: $rot_cockwise
    on_anticlockwise:
        if:
          condition:
            sensor.in_range:
              id: d5525
              below: 49.0
          then:      
            - homeassistant.service:
                service: $rot_Service_1
                data:
                  entity_id: $rot_countercockwise


light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    id: light_1
    pin: RX
    num_leds: 2
    effects:     
      - pulse:        


  - platform: partition
    id: light_1b
    segments:
      - id: light_1
        from: 1
        to: 1
        
  - platform: partition
    id: light_2b    
    segments:
      - id: light_1
        from: 0
        to: 0


binary_sensor:
  - platform: homeassistant
    entity_id: $pixel_1
    id: outside_door
    on_state:
          - light.turn_off: light_1b
          - delay: 1s
          - if:
              condition:
                - binary_sensor.is_on: outside_door
              then:          
              - light.turn_on: 
                    id: light_1b
                    brightness: $light_1
                    red: 100%
                    green: 0%
                    blue: 0% 
          - if:
              condition:
                - binary_sensor.is_off: outside_door
              then:          
              - light.turn_on: 
                    id: light_1b
                    brightness: $light_1
                    red: 0%
                    green: 100%
                    blue: 0%                     

  - platform: homeassistant
    entity_id: $pixel_2
    id: heater_door
    on_state:
          - light.turn_off: light_2b
          - delay: 1s
          - if:
              condition:
                - binary_sensor.is_on: heater_door
              then:          
              - light.turn_on: 
                    id: light_2b
                    brightness: $light_2
                    red: 100%
                    green: 0%
                    blue: 0% 
          - if:
              condition:
                - binary_sensor.is_off: heater_door
              then:          
              - light.turn_on: 
                    id: light_2b
                    brightness: $light_2
                    red: 0%
                    green: 100%
                    blue: 0%  


            
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
    id: davidbutton3    
    filters:
      - invert:     
    on_multi_click:
        - timing:
            - ON for at least 0.5s
          then:
            - homeassistant.service:
                service: $button_Service_1_hold
                data:
                  entity_id: $button_1_hold
            - logger.log: "Double-Clicked"
        - timing:
            - ON for at most .5s
            - OFF for at least 0.5s
          then:
            - homeassistant.service:
                service: $button_Service_1_click
                data:
                  entity_id: $button_1_click
            - logger.log: "Single-Clicked" 
            
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
    id: davidbutton4    
    filters:
      - invert:     
    on_multi_click:
        - timing:
            - ON for at least 0.5s
          then:
            - homeassistant.service:
                service: $button_Service_2_hold
                data:
                  entity_id: $button_2_hold
            - logger.log: "Double-Clicked"
        - timing:
            - ON for at most .5s
            - OFF for at least 0.5s
          then:
            - homeassistant.service:
                service: $button_Service_2_click
                data:
                  entity_id: $button_2_click
            - logger.log: "Single-Clicked"

  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    id: davidbutton5    
    filters:
      - invert:     
    on_multi_click:
        - timing:
            - ON for at least 0.5s
          then:
            - homeassistant.service:
                service: $button_Service_3_hold
                data:
                  entity_id: $button_3_hold    
            - logger.log: "Double-Clicked"
        - timing:
            - ON for at most .5s
            - OFF for at least 0.5s
          then:
            - homeassistant.service:
                service: $button_Service_3_click
                data:
                  entity_id: $button_3_click
            - logger.log: "Single-Clicked"  
          
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    id: davidbutton6    
    filters:
      - invert:     
    on_multi_click:
        - timing:
            - ON for at least 0.5s
          then:
            - homeassistant.service:
                service: $button_Service_4_hold
                data:
                  entity_id: $button_4_hold     
            - logger.log: "Double-Clicked"
        - timing:
            - ON for at most .5s
            - OFF for at least 0.5s
          then:
            - homeassistant.service:
                service: $button_Service_4_click
                data:
                  entity_id: $button_4_click
            - logger.log: "Single-Clicked"       
      
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
    id: davidbutton7    
    filters:
      - invert:     
    on_multi_click:
        - timing:
            - ON for at least 0.5s
          then:
            - homeassistant.service:
                service: $push_button_service
                data:
                  entity_id: $push_button       
            - logger.log: "Double-Clicked"
        - timing:
            - ON for at most .5s
            - OFF for at least 0.5s
          then:
            - homeassistant.service:
                service: $push_button_service
                data:
                  entity_id: $push_button   
            - logger.log: "Single-Clicked"                 


    